theme = "soho"
baseurl = "/"
relativeurls = false
title = "Fernando A. Zepeda H."
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
math = true

[params]
profilePicture = "images/FAZH_03.jpeg"
copyright = "Fernando Antonio Zepeda Herrera"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
disqusShortname = "fazepher"


  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/fernando-antonio-zepeda-herrera-385878166/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/fazepher"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/fazepher"

[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "posts"
  url = "/post/"
  
  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/project/"
  
  [[menu.main]]
  name = "About me"
  identifier = "about"
  weight = 300
  url = "/about/"
  

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
